# Auto-generated by scripts/gen-formula.sh on each release. Do not edit by hand.
class Mcc < Formula
  desc "Run multiple Claude Code CLI profiles on one device"
  homepage "https://github.com/husseinAbdElaziz/multi-claude"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/husseinAbdElaziz/multi-claude/releases/download/v0.2.0/mcc-macos-arm64.tar.gz"
      sha256 "3578b2916b73b9c8100ab57dba511b1311b0742bfacc54e827e06ef3ce3fc740"
    else
      url "https://github.com/husseinAbdElaziz/multi-claude/releases/download/v0.2.0/mcc-macos-x64.tar.gz"
      sha256 "d33c6f23d6dc8340c5b68f82dfcd22b6cb3a658315532041826339d13f284217"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/husseinAbdElaziz/multi-claude/releases/download/v0.2.0/mcc-linux-arm64.tar.gz"
      sha256 "13825760de0e68d4e893a0c2e7b19c01cdf3e5e92e4f3c6c085d7688ae567bc7"
    else
      url "https://github.com/husseinAbdElaziz/multi-claude/releases/download/v0.2.0/mcc-linux-x64.tar.gz"
      sha256 "9646518c5af922f3320c38bed730b42658b3986cff575b9f240b85d2fd9b633f"
    end
  end

  def install
    bin.install "mcc"
  end

  def caveats
    <<~EOS
      mcc launches the Claude Code CLI, so make sure `claude` is installed and on
      your PATH: https://docs.anthropic.com/en/docs/claude-code
    EOS
  end

  test do
    assert_match "mcc #{version}", shell_output("#{bin}/mcc --version")
  end
end
