# Auto-generated by scripts/gen-formula.sh on each release. Do not edit by hand.
class Mcc < Formula
  desc "Run multiple Claude Code CLI profiles on one device"
  homepage "https://github.com/husseinAbdElaziz/multi-claude"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/husseinAbdElaziz/multi-claude/releases/download/v0.4.0/mcc-macos-arm64.tar.gz"
      sha256 "3a4e1655605f1b9bfc7673916380804ea4db4eafa6046ddf5a9054a13aee117f"
    else
      url "https://github.com/husseinAbdElaziz/multi-claude/releases/download/v0.4.0/mcc-macos-x64.tar.gz"
      sha256 "2cdd0af386360236a51d36d4f6a49ea9d813a2232dde49b501f99760f4638faa"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/husseinAbdElaziz/multi-claude/releases/download/v0.4.0/mcc-linux-arm64.tar.gz"
      sha256 "e1841311f2fdb7306c15ceb50fd92d39eaf15ce41ebdfc98de5c7964b82845d7"
    else
      url "https://github.com/husseinAbdElaziz/multi-claude/releases/download/v0.4.0/mcc-linux-x64.tar.gz"
      sha256 "20e5c072dca4f77cbea3ed8ff53fe5fd42610c5bd089b9ecf77ad7c38c013e55"
    end
  end

  def install
    bin.install "mcc"
  end

  def caveats
    <<~EOS
      mcc launches the Claude Code CLI, so make sure `claude` is installed and on
      your PATH: https://docs.anthropic.com/en/docs/claude-code
    EOS
  end

  test do
    assert_match "mcc #{version}", shell_output("#{bin}/mcc --version")
  end
end
