# Auto-generated by scripts/gen-formula.sh on each release. Do not edit by hand.
class Mcc < Formula
  desc "Run multiple Claude Code CLI profiles on one device"
  homepage "https://github.com/husseinAbdElaziz/multi-claude"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/husseinAbdElaziz/multi-claude/releases/download/v0.6.0/mcc-macos-arm64.tar.gz"
      sha256 "0672ba04fd43f747b6979efa600c22e0f58904bf37d2425d9d14680aadf9e2bc"
    else
      url "https://github.com/husseinAbdElaziz/multi-claude/releases/download/v0.6.0/mcc-macos-x64.tar.gz"
      sha256 "f6bd250d70c07b51c80a5660a48214c9758c6cbabf4063641c9aeb310a1d7fde"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/husseinAbdElaziz/multi-claude/releases/download/v0.6.0/mcc-linux-arm64.tar.gz"
      sha256 "a0daeb1ae5b09ec3cfae662511448c2d5236ab80645103f6803b47fb532b6c68"
    else
      url "https://github.com/husseinAbdElaziz/multi-claude/releases/download/v0.6.0/mcc-linux-x64.tar.gz"
      sha256 "f8c0820a4c6388ddc24a609770aba409b1e1ca1e9cf675458d1e8f63c2a5430c"
    end
  end

  def install
    bin.install "mcc"
  end

  def caveats
    <<~EOS
      mcc launches the Claude Code CLI, so make sure `claude` is installed and on
      your PATH: https://docs.anthropic.com/en/docs/claude-code
    EOS
  end

  test do
    assert_match "mcc #{version}", shell_output("#{bin}/mcc --version")
  end
end
